# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerUse < Formula
  desc "CLI to manage multiple Docker Hub accounts"
  homepage "https://github.com/chiragagg5k/docker-use"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ChiragAgg5k/docker-use/releases/download/v0.1.4/docker-use_0.1.4_darwin_x86_64.tar.gz"
      sha256 "85c497925b95751ea2bd4a24292a33c686a967230d4fec713d17c9f1a0fd5e17"

      define_method(:install) do
        bin.install "docker-use"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ChiragAgg5k/docker-use/releases/download/v0.1.4/docker-use_0.1.4_darwin_arm64.tar.gz"
      sha256 "d9972e1f082e0a2b872ae1b13f29f079802dc9db11d88271e27d767448d5a5a5"

      define_method(:install) do
        bin.install "docker-use"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ChiragAgg5k/docker-use/releases/download/v0.1.4/docker-use_0.1.4_linux_x86_64.tar.gz"
      sha256 "54ae8a9f0d8b9a0a49befe64db2a38163fa4b200d525db1ecebb1776e3ba5d3e"
      define_method(:install) do
        bin.install "docker-use"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ChiragAgg5k/docker-use/releases/download/v0.1.4/docker-use_0.1.4_linux_arm64.tar.gz"
      sha256 "d155ece9de768b437033b133474cbb96a1fee088c1e23df187c23a7f05db03ce"
      define_method(:install) do
        bin.install "docker-use"
      end
    end
  end

  test do
    system "#{bin}/docker-use --help"
  end
end
